// Attempt logging.
//
// This route was the weakest thing in the API and it is worth being explicit
// about why, because none of it was obvious from reading it:
//
//   * `await c.req.json()` with no try/catch — malformed JSON threw out of the
//     handler, and Hono's default error handler answered with the thrown
//     message
//   * `body.answers` was checked for "array, non-empty" and then handed
//     straight to computeScore, which iterates it. A 100,000-element array of
//     anything was accepted and walked
//   * `durationSeconds` was unvalidated, so `Math.round(undefined)` bound NaN
//     into a D1 integer column
//   * `challengePublicId` was an unbounded string going into a query
//   * and it is the only route in the product that WRITES to D1 without any
//     identity behind it, at one row per request
//
// The score itself is recomputed here from the submitted answers and never read
// from the client, which was already true and stays true: the number that gets
// stored is the server's.
//
// What is honestly NOT claimed: the per-answer `correct` flags are the client's
// account of its own quiz. A single-player attempt row is a statistic, not a
// leaderboard — there is no ranking, nothing is awarded, and nothing else reads
// it — so re-deriving every answer against the question bank would cost a
// multi-row D1 read per submission to protect a number nobody competes on. The
// place where answer correctness genuinely cannot be trusted is multiplayer, and
// there it is decided entirely by the room, never by the client.

import { Hono } from "hono";
import type { Env } from "../env";
import { computeScore } from "../../shared/scoring";
import type { AnswerRecord } from "../../shared/types";
import { getChallengeRowIdByPublicId, insertAttempt } from "../db/attempts";
import { gate } from "../lib/ratelimit";

export const attemptRoutes = new Hono<{ Bindings: Env }>();

/** The longest quiz the product can produce is 30 questions; this is slack, not a target. */
const MAX_ANSWERS = 60;
/** Public ids are generated by the server and are nowhere near this long. */
const MAX_PUBLIC_ID_LENGTH = 64;
/** Twelve hours. Anything beyond it is a broken clock or a fabricated number. */
const MAX_DURATION_SECONDS = 43_200;

/**
 * Keeps only the fields scoring reads, with the types it expects.
 *
 * Rebuilt field by field rather than cast, so an object with two hundred extra
 * keys contributes nothing but the five that matter, and a `correct` of
 * `"yes"` counts as false rather than as truthy.
 */
function parseAnswers(value: unknown): AnswerRecord[] | null {
  if (!Array.isArray(value)) return null;
  if (value.length === 0 || value.length > MAX_ANSWERS) return null;

  const answers: AnswerRecord[] = [];
  for (const item of value) {
    if (typeof item !== "object" || item === null) return null;
    const row = item as Record<string, unknown>;
    const answer: AnswerRecord = {
      questionId: Number.isInteger(row.questionId) ? (row.questionId as number) : 0,
      selectedOptionId: Number.isInteger(row.selectedOptionId) ? (row.selectedOptionId as number) : null,
      correct: row.correct === true,
      revealed: row.revealed === true,
      hintsUsed:
        typeof row.hintsUsed === "number" && Number.isFinite(row.hintsUsed)
          ? Math.min(10, Math.max(0, Math.trunc(row.hintsUsed)))
          : 0,
      timeMs:
        typeof row.timeMs === "number" && Number.isFinite(row.timeMs)
          ? Math.min(MAX_DURATION_SECONDS * 1000, Math.max(0, Math.round(row.timeMs)))
          : 0,
    };
    // Free text only; absent rather than null, which is what the type says.
    if (typeof row.typedAnswer === "string") answer.typedAnswer = row.typedAnswer.slice(0, 200);
    answers.push(answer);
  }
  return answers;
}

attemptRoutes.post("/", async (c) => {
  const limited = await gate(c, "RL_WRITE", "attempt");
  if (limited) return limited;

  let body: unknown;
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: "Invalid JSON body" }, 400);
  }
  if (typeof body !== "object" || body === null) {
    return c.json({ error: "Invalid request body" }, 400);
  }
  const b = body as Record<string, unknown>;

  const answers = parseAnswers(b.answers);
  if (!answers) return c.json({ error: "answers required" }, 400);

  const duration =
    typeof b.durationSeconds === "number" && Number.isFinite(b.durationSeconds)
      ? Math.min(MAX_DURATION_SECONDS, Math.max(0, Math.round(b.durationSeconds)))
      : 0;

  const publicId =
    typeof b.challengePublicId === "string" && b.challengePublicId.length > 0
      ? b.challengePublicId.slice(0, MAX_PUBLIC_ID_LENGTH)
      : null;

  const score = computeScore(answers);

  const challengeId = publicId ? await getChallengeRowIdByPublicId(c.env.DB, publicId) : null;

  const attemptId = await insertAttempt(c.env.DB, {
    challengeId,
    score: score.points,
    questionCount: score.total,
    durationSeconds: duration,
  });

  return c.json({ attemptId, score });
});
