// Generates migrations/../seed/seed.sql from seed/questions.ts
// Run with: node scripts/build-seed.mjs
import { writeFileSync } from "node:fs";
import { seedQuestions } from "../seed/questions.ts";

function sqlEscape(value) {
  return String(value).replace(/'/g, "''");
}

function assertQuestion(q, idx) {
  const errors = [];
  if (!Array.isArray(q.options) || q.options.length !== 4) {
    errors.push(`question #${idx} must have exactly 4 options`);
  }
  if (typeof q.correctIndex !== "number" || q.correctIndex < 0 || q.correctIndex > 3) {
    errors.push(`question #${idx} correctIndex out of range`);
  }
  if ((q.mode === "WHO_AM_I" || q.mode === "CAREER_PATH") && (!q.clues || q.clues.length < 2)) {
    errors.push(`question #${idx} (${q.mode}) needs at least 2 clues`);
  }
  if (!q.scopes || q.scopes.length === 0) {
    errors.push(`question #${idx} has no scopes`);
  }
  if (errors.length) throw new Error(errors.join("; "));
}

const lines = [];
lines.push("-- Auto-generated by scripts/build-seed.mjs — do not edit by hand.");
lines.push("-- Regenerate with: node scripts/build-seed.mjs");
lines.push("DELETE FROM question_scopes;");
lines.push("DELETE FROM question_clues;");
lines.push("DELETE FROM question_options;");
lines.push("DELETE FROM questions;");
lines.push("");

let counts = { total: 0, byDifficulty: {}, byMode: {} };

seedQuestions.forEach((q, idx) => {
  assertQuestion(q, idx);
  counts.total++;
  counts.byDifficulty[q.difficulty] = (counts.byDifficulty[q.difficulty] || 0) + 1;
  counts.byMode[q.mode] = (counts.byMode[q.mode] || 0) + 1;

  // Question ids are assigned explicitly from the position in questions.ts so
  // that re-seeding is stable: previously shared challenge links and stored
  // daily quizzes keep pointing at the same questions. This makes the file
  // append-only in practice — reordering or deleting entries would reassign
  // ids and orphan existing challenges.
  const id = idx + 1;
  const publicId = `q_${String(id).padStart(4, "0")}`;
  lines.push(
    `INSERT INTO questions (id, public_id, mode, category, difficulty, question_he, explanation_he, verified, active, source_label) VALUES (${id}, '${publicId}', '${q.mode}', '${q.category}', '${q.difficulty}', '${sqlEscape(q.questionHe)}', '${sqlEscape(q.explanationHe)}', 1, 1, '${sqlEscape(q.sourceLabel)}');`
  );
  q.options.forEach((opt, optIdx) => {
    lines.push(
      `INSERT INTO question_options (question_id, answer_text, is_correct, sort_order) VALUES (${id}, '${sqlEscape(
        opt
      )}', ${optIdx === q.correctIndex ? 1 : 0}, ${optIdx});`
    );
  });
  (q.clues || []).forEach((clue, clueIdx) => {
    lines.push(
      `INSERT INTO question_clues (question_id, clue_he, sort_order) VALUES (${id}, '${sqlEscape(clue)}', ${clueIdx});`
    );
  });
  (q.scopes || []).forEach((scope) => {
    lines.push(
      `INSERT INTO question_scopes (question_id, scope_type, scope_value) VALUES (${id}, '${scope.type}', '${sqlEscape(
        scope.value
      )}');`
    );
  });
  lines.push("");
});

writeFileSync(new URL("../seed/seed.sql", import.meta.url), lines.join("\n"));

console.log(`Generated seed/seed.sql with ${counts.total} questions.`);
console.log("By difficulty:", counts.byDifficulty);
console.log("By mode:", counts.byMode);
