// Builds seed/seed.sql from curated questions + generated questions.
// Run with: node scripts/build-seed.mjs
//
// ID STABILITY
// Curated questions take ids from their position in seed/questions.ts (1..N),
// so that file must stay append-only. Generated questions take ids from
// seed/generated-ids.json, a ledger keyed by semantic key — a key keeps its id
// forever, new keys get the next free id. Both rules exist so that shared
// challenge links and stored daily quizzes keep resolving after a re-seed.

import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { seedQuestions } from "../seed/questions.ts";
import { generateAll } from "../seed/generators/index.ts";
import { CLUBS } from "../seed/data/clubs.ts";
import { PLAYERS } from "../seed/data/players.ts";
import { normalizeAnswer } from "../src/shared/answerMatching.ts";

const LEDGER_PATH = new URL("../seed/generated-ids.json", import.meta.url);
const GENERATED_ID_BASE = 100000;

function sqlEscape(value) {
  return String(value).replace(/'/g, "''");
}

// ---------------------------------------------------------------------------
// Curated questions get free-text support for free when their correct answer
// is a club or player we already hold aliases for.
// ---------------------------------------------------------------------------
const entityByHebrewName = new Map();
for (const c of CLUBS) entityByHebrewName.set(c.he, { canonical: c.he, aliases: [c.en, ...c.aliases] });
for (const p of PLAYERS) entityByHebrewName.set(p.he, { canonical: p.he, aliases: [p.en, ...p.aliases] });

function curatedFreeTextSpec(question) {
  const correct = question.options[question.correctIndex];
  const entity = entityByHebrewName.get(correct);
  if (!entity) return null;
  return { canonical: entity.canonical, aliases: entity.aliases };
}

// ---------------------------------------------------------------------------
function assertCurated(q, idx) {
  const errors = [];
  if (!Array.isArray(q.options) || q.options.length !== 4) errors.push(`#${idx} needs exactly 4 options`);
  if (new Set(q.options).size !== 4) errors.push(`#${idx} has duplicate options`);
  if (typeof q.correctIndex !== "number" || q.correctIndex < 0 || q.correctIndex > 3) {
    errors.push(`#${idx} correctIndex out of range`);
  }
  if ((q.mode === "WHO_AM_I" || q.mode === "CAREER_PATH") && (!q.clues || q.clues.length < 2)) {
    errors.push(`#${idx} (${q.mode}) needs at least 2 clues`);
  }
  if (!q.scopes || q.scopes.length === 0) errors.push(`#${idx} has no scopes`);
  if (errors.length) throw new Error(errors.join("; "));
}

const lines = [];
lines.push("-- Auto-generated by scripts/build-seed.mjs — do not edit by hand.");
lines.push("-- Regenerate with: node scripts/build-seed.mjs");
lines.push("DELETE FROM answer_aliases;");
lines.push("DELETE FROM question_hints;");
lines.push("DELETE FROM question_scopes;");
lines.push("DELETE FROM question_clues;");
lines.push("DELETE FROM question_options;");
lines.push("DELETE FROM questions;");
lines.push("");

const stats = { curated: 0, generated: 0, freeText: 0, byDifficulty: {}, byMode: {}, byCategory: {} };

function emitQuestion({ id, publicId, q, semanticKey, generated, freeTextSpec, hints }) {
  stats.byDifficulty[q.difficulty] = (stats.byDifficulty[q.difficulty] || 0) + 1;
  stats.byMode[q.mode] = (stats.byMode[q.mode] || 0) + 1;
  stats.byCategory[q.category] = (stats.byCategory[q.category] || 0) + 1;

  const supportsFreeText = freeTextSpec ? 1 : 0;
  if (supportsFreeText) stats.freeText++;

  lines.push(
    `INSERT INTO questions (id, public_id, mode, category, difficulty, question_he, explanation_he, verified, active, source_label, canonical_answer, supports_free_text, semantic_key, generated) VALUES (` +
      `${id}, '${publicId}', '${q.mode}', '${q.category}', '${q.difficulty}', '${sqlEscape(q.questionHe)}', ` +
      `'${sqlEscape(q.explanationHe)}', 1, 1, '${sqlEscape(q.sourceLabel)}', ` +
      `${freeTextSpec ? `'${sqlEscape(freeTextSpec.canonical)}'` : "NULL"}, ${supportsFreeText}, ` +
      `${semanticKey ? `'${sqlEscape(semanticKey)}'` : "NULL"}, ${generated});`
  );

  q.options.forEach((opt, optIdx) => {
    lines.push(
      `INSERT INTO question_options (question_id, answer_text, is_correct, sort_order) VALUES (${id}, '${sqlEscape(
        opt
      )}', ${optIdx === q.correctIndex ? 1 : 0}, ${optIdx});`
    );
  });

  (q.clues || []).forEach((clue, i) => {
    lines.push(
      `INSERT INTO question_clues (question_id, clue_he, sort_order) VALUES (${id}, '${sqlEscape(clue)}', ${i});`
    );
  });

  (q.scopes || []).forEach((scope) => {
    lines.push(
      `INSERT INTO question_scopes (question_id, scope_type, scope_value) VALUES (${id}, '${scope.type}', '${sqlEscape(
        scope.value
      )}');`
    );
  });

  if (freeTextSpec) {
    const seenAlias = new Set();
    for (const alias of [freeTextSpec.canonical, ...freeTextSpec.aliases]) {
      if (!alias || typeof alias !== "string") continue;
      const normalized = normalizeAnswer(alias);
      if (!normalized || seenAlias.has(normalized)) continue;
      seenAlias.add(normalized);
      const lang = /[֐-׿]/.test(alias) ? "he" : "en";
      lines.push(
        `INSERT INTO answer_aliases (question_id, alias, normalized, lang) VALUES (${id}, '${sqlEscape(
          alias
        )}', '${sqlEscape(normalized)}', '${lang}');`
      );
    }
  }

  (hints || []).forEach((hint, i) => {
    lines.push(
      `INSERT INTO question_hints (question_id, text, order_index) VALUES (${id}, '${sqlEscape(hint)}', ${i});`
    );
  });

  lines.push("");
}

// ---------------------------------------------------------------------------
// 1. Curated questions — ids 1..N by position (file is append-only).
// ---------------------------------------------------------------------------
seedQuestions.forEach((q, idx) => {
  assertCurated(q, idx);
  stats.curated++;
  const id = idx + 1;
  emitQuestion({
    id,
    publicId: `q_${String(id).padStart(4, "0")}`,
    q,
    semanticKey: null,
    generated: 0,
    freeTextSpec: curatedFreeTextSpec(q),
    hints: [],
  });
});

// ---------------------------------------------------------------------------
// 2. Generated questions — ids from the persistent ledger.
// ---------------------------------------------------------------------------
const generated = generateAll();
const ledger = existsSync(LEDGER_PATH) ? JSON.parse(readFileSync(LEDGER_PATH, "utf8")) : {};
let nextId = Math.max(GENERATED_ID_BASE - 1, ...Object.values(ledger).map(Number)) + 1;

for (const q of generated) {
  if (ledger[q.semanticKey] === undefined) {
    ledger[q.semanticKey] = nextId++;
  }
  const id = ledger[q.semanticKey];
  stats.generated++;
  emitQuestion({
    id,
    publicId: `g_${id}`,
    q,
    semanticKey: q.semanticKey,
    generated: 1,
    freeTextSpec: q.freeText && q.canonicalAnswer ? { canonical: q.canonicalAnswer, aliases: q.aliases ?? [] } : null,
    hints: q.hints ?? [],
  });
}

writeFileSync(LEDGER_PATH, JSON.stringify(ledger, null, 0));
writeFileSync(new URL("../seed/seed.sql", import.meta.url), lines.join("\n"));

const total = stats.curated + stats.generated;
console.log(`Generated seed/seed.sql`);
console.log(`  total questions : ${total}  (curated ${stats.curated}, generated ${stats.generated})`);
console.log(`  free-text ready : ${stats.freeText}`);
console.log(`  by difficulty   :`, stats.byDifficulty);
console.log(`  by mode         :`, stats.byMode);
console.log(`  by category     :`, stats.byCategory);
